// Generated by IcedCoffeeScript 1.6.2a
(function() {
  var makeScratch;



  makeScratch = function(el) {
    var $cover, $el, context, cover, height, left, top, width, _ref;
    $el = $(el);
    width = $el.innerWidth();
    height = $el.innerHeight();
    _ref = $el.offset(), top = _ref.top, left = _ref.left;
    $cover = $('<canvas class="scratch-cover">').appendTo(el);
    cover = $cover[0];
    cover.width = width;
    cover.height = height;
    context = cover.getContext('2d');
    context.fillStyle = '#666';
    return context.fillRect(0, 0, width, height);
  };

  $(function() {
    return $('.scratch').each(function() {
      return makeScratch(this);
    });
  });

}).call(this);
